= 测试Vert.x代码

TIP: 相应的源代码位于指南存储库的step-4文件夹中。

到目前为止，我们一直在开发未经测试的wiki实现。这当然不是一个好的做法，所以让我们看看如何编写Vert.x代码的测试。

== 开始

`vertx-unit` 模块提供了用于在Vert.x中测试异步操作的实用程序。除此之外，你可以使用像JUnit这样的测试框架。

使用JUnit，所需的Maven依赖关系如下：

[source,xml,indent=0]
----
include::pom.xml[tags=test-deps]
----

JUnit测试需要使用`VertxUnitRunner` 运行器进行注释，以使用 `vertx-unit` 特性：

[source,java]
----
@RunWith(VertxUnitRunner.class)
public class SomeTest {
  // (...)
}
----

使用该运行器，JUnit测试和生命周期方法接受 `TestContext` 参数。这个对象提供了对基本断言的访问，存储数据的上下文以及我们将在本节中看到的一些面向异步的助手。

为了说明这一点，让我们考虑一个异步场景，我们要检查定时器任务是否被调用过一次，并且定时任务被调用了3次。由于该代码是异步的，所以测试方法在测试完成之前退出，因此使测试通过或失败也需要以异步方式完成：

[source,java,indent=0]
----
include::src/test/java/io/vertx/guides/wiki/database/WikiDatabaseVerticleTest.java[tags=async-basic]
----
<1> `TestContext` 是运行器提供的参数。
<2> 由于我们在单元测试中，我们需要创建一个Vert.x上下文。
<3> 这是一个基本的 `TestContext` 断言的例子。
<4> 我们得到第一个 `Async` 对象，以后可以完成（或失败）。
<5> 这个 `Async` 对象作为一个倒计时，在3次调用后成功完成。
<6> 定时器启动时我们完成。
<7> 每个周期性任务滴答触发一个倒计时。当所有 `Async `对象完成时，测试通过。
<8> 异步测试用例有一个默认（很长）的超时，但是可以通过JUnit `@Test` 注解来覆盖。

== 测试数据库操作

数据库服务非常适合编写测试。

我们首先需要部署数据库verticle。我们将把JDBC连接配置成带有内存存储的HSQLDB，一旦成功，我们将为我们的测试用例获取一个服务代理。

由于这些操作涉及到，所以我们在生命周期方法之前/之后利用JUnit

[source,java,indent=0]
----
include::src/test/java/io/vertx/guides/wiki/database/WikiDatabaseVerticleTest.java[tags=prepare]
----
<1> 我们只覆盖一些verticle设置，其他的将有默认值。
<2> `asyncAssertSuccess` 对于提供一个检查异步操作是否成功的处理程序非常有用。有一个没有参数的变体，像这样的变体，我们可以将结果链接到另一个处理程序。

清理Vert.x上下文很简单，我们再次使用 `asyncAssertSuccess` 来确保没有遇到错误：

[source,java,indent=0]
----
include::src/test/java/io/vertx/guides/wiki/database/WikiDatabaseVerticleTest.java[tags=finish]
----

服务操作本质上是CRUD操作，所以将所有这些测试用例组合起来的JUnit测试用例是一种很好的测试方法：

[source,java,indent=0]
----
include::src/test/java/io/vertx/guides/wiki/database/WikiDatabaseVerticleTest.java[tags=crud]
----
<1> 这是唯一的 `异步` 最终完成。
<2> 这是退出测试用例方法并依赖JUnit超时的替代方法。这里测试用例线程的执行会一直等待，直到 `异步` 完成或者超时时间结束。
