= 结尾

这是本指南的结尾。 让我们花点时间重述前几节中的重要内容，然后指出更多有用的资源。

== 概要

我们通过使用Vert.x构建wiki Web应用程序来开始本指南。虽然第一次迭代是 _"敏捷和杂乱的快速原型"_ 的典型代表，但它表明，可以快速轻松地构建这样一个应用程序，使用Web模板的服务器端渲染以及关系数据库的持久性。

接下来的步骤展示了如何通过连续的重构来改进设计：首先将每个技术关注点分离为独立的Verticle，然后提取Vert.x服务以获得简洁的API，最后介绍了对异步代码进行JUnit测试。

然后，我们开始使用Web客户端API来调用第三方HTTP/JSON服务，这进一步简化了Vert.x核心中HTTP客户端的使用。相反，我们还看到了如何使用优雅的Vert.x Web模块发布HTTP/JSON Web API。

从那里可以很容易地获得构建为许多服务提供对外接口的API网关的方法。如果你要建立这样的网关，我们建议你利用：

* Vert.x RxJava支持来描述服务消费数据流， 
* Vert.x断路器模块能够始终如一地处理服务的潜在故障。

访问控制，认证和安全性往往被忽视或产生不好的后果。我们看到Vert.x提供了一个简单的可插式的利用数据库，文件或LDAP目录的身份验证机制。 SSL网络加密非常容易在服务器上设置或客户端使用。最后，Vert.x支持JWT令牌，这是一种非常有用且分布式的Web API认证方案。

Vert.x核心API依赖于回调，因为它是处理异步事件的最通用的方式。 Vert.x提供了一个简单的异步API。虽然Vert.x的异步是可组合的，但它们应局限于有限的用途，例如处理verticle的部署和初始化。我们看到了Vert.x如何支持RxJava，我们鼓励您将它用于您自己的Verticle中。更重要的是，RxJava是JVM上最受欢迎的响应式编程库，因此您可以轻松找到第三方库，以便始终集成到您的端到端响应式应用程序中。

现代Web应用程序倾向于让服务器公开HTTP/JSON API，并依赖于用户界面的客户端Web框架。我们看到了如何使用AngularJS来实现这一点，从而将我们的wiki变成一个单页面的应用程序。

最后，我们看到扩展应用程序的事件总线的优雅性，以允许Web应用程序使用SockJS桥接器从浏览器发送和接收事件。虽然它最初看起来可能是一个小功能，但实际上它大大简化了 _实时_ Web应用程序功能的开发。在使用HTTP端点的情况下，SockJS桥实际上也很有用：在事件总线上发送消息然后获得响应有时可能比做HTTP调用更简单，让服务器处理HTTP请求并转发它到事件总线上的Verticle，并最终通过编码JSON响应来终止HTTP交换。

== 进一步

http://vertx.io/[Vert.x网站] 当然是所有有关Vert.x的权威。

我们没有在本指南中介绍过许多功能和模块，例如：

* 使用Hazelcast, Infinispan, Apache Ignite或Apache Zookeeper进行集群,
* 代码如何与其他支持的语言一起使用，
* 使用gRPC可能(但不一定)通过HTTP/2进行发布和调用
* 使用MongoDB或Redis等NoSQL数据库，
* 通过SMTP发送电子邮件，
* 与AMQP，Stomp，Kafka，MQTT或RabbitMQ进行消息传递，
* 使用来自定制和热门提供商的OAuth2身份验证，
* 用于编写阻塞式代码的Vert.x同步，后者在运行时转换为多线程非阻塞代码，
* 发布和发现注册管理机构的微服务，例如在OpenShift等云环境中进行部署时，
* 暴露指标和健康检查。

此列表并非详尽无遗：Vert.x是一个工具包，因此您可以决定项目所需的成分大小。

您也可能发现浏览 https://github.com/vert-x3/vertx-awesome[Vert.x awesome] 社区项目列表非常有用，因为它超出了项目支持的范围。

如果您正在开发微服务，我们建议您阅读由ClémentEscoffier撰写的 https://developers.redhat.com/promotions/building-reactive-microservices-in-java/["Java中构建响应式微服务"] 一书。

== 这就是所有人!

我们希望您喜欢阅读本指南，结果证明它对于您使用Vert.x进行异步编程的过程非常有用。

随时可以通过电子邮件或通过 https://groups.google.com/forum/?fromgroups#!forum/vertx/[Vert.x项目用户组] 与作者取得联系。 当然，我们赞赏表扬，但我们非常赞赏任何可以改进此内容的建设性反馈。

非常感谢!
