= 结尾

这是本指南的结尾。 让我们花点时间重述前几节中的重要内容，然后指出更多有用的资源。

== 概要

我们通过使用Vert.x构建wiki Web应用程序来开始本指南。虽然第一次迭代是 _"敏捷和杂乱的快速原型"_ 的典型代表，但它表明，可以快速轻松地构建这样一个应用程序，使用Web模板的服务器端渲染以及关系数据库的持久性。

接下来的步骤展示了如何通过连续的重构来改进设计：首先将每个技术关注点分离为独立的Verticle，然后提取Vert.x服务以获得简洁的API，最后介绍了对异步代码进行JUnit测试。

然后，我们开始使用Web客户端API来调用第三方HTTP/JSON服务，这进一步简化了Vert.x核心中HTTP客户端的使用。相反，我们还看到了如何使用优雅的Vert.x Web模块发布HTTP/JSON Web API。

从那里可以很容易地获得构建为许多服务提供对外接口的API网关的方法。如果你要建立这样的网关，我们建议你利用：

* Vert.x RxJava支持来描述服务消费数据流， 
* Vert.x断路器模块能够始终如一地处理服务的潜在故障。

访问控制，认证和安全性往往被忽视或产生不好的后果。我们看到Vert.x提供了一个简单的可插式的利用数据库，文件或LDAP目录的身份验证机制。 SSL网络加密非常容易在服务器上设置或客户端使用。最后，Vert.x支持JWT令牌，这是一种非常有用且分布式的Web API认证方案。

Vert.x核心API依赖于回调，因为它是处理异步事件的最通用的方式。 Vert.x提供了一个简单的异步API。虽然Vert.x的异步是可组合的，但它们应局限于有限的用途，例如处理verticle的部署和初始化。我们看到了Vert.x如何支持RxJava，我们鼓励您将它用于您自己的Verticle中。更重要的是，RxJava是JVM上最受欢迎的响应式编程库，因此您可以轻松找到第三方库，以便始终集成到您的端到端响应式应用程序中。

现代Web应用程序倾向于让服务器公开HTTP/JSON API，并依赖于用户界面的客户端Web框架。我们看到了如何使用AngularJS来实现这一点，从而将我们的wiki变成一个单页面的应用程序。

最后，我们看到扩展应用程序的事件总线的优雅性，以允许Web应用程序使用SockJS桥接器从浏览器发送和接收事件。虽然它最初看起来可能是一个小功能，但实际上它大大简化了 _实时_ Web应用程序功能的开发。在使用HTTP端点的情况下，SockJS桥实际上也很有用：在事件总线上发送消息然后获得响应有时可能比做HTTP调用更简单，让服务器处理HTTP请求并转发它到事件总线上的Verticle，并最终通过编码JSON响应来终止HTTP交换。

== Going further

The http://vertx.io/[Vert.x website] is of course the authority on all things Vert.x.

There are many features and modules that we haven't covered in this guide, such as:

* clustering using Hazelcast, Infinispan, Apache Ignite or Apache Zookeeper,
* how the code looks like with other supported languages,
* exposing and consuming over HTTP/2, possibly (but not necessarily) with gRPC 
* using NoSQL databases such as MongoDB or Redis,
* sending emails over SMTP,
* messaging with AMQP, Stomp, Kafka, MQTT or RabbitMQ,
* using OAuth2 authentication from custom and popular providers,
* Vert.x sync for writing blocking-style code that is later turned into _fibers_ non-blocking code at runtime,
* publishing and discovering micro-services from registries, for instance when deploying on cloud environments like OpenShift,
* exposing metrics and health checks.

This list is not exhaustive: Vert.x is a toolkit so you are the one to decide what ingredients are required for your project, big or small.

You may also find it useful to browse the https://github.com/vert-x3/vertx-awesome[Vert.x awesome] curated list of community projects as it goes beyond what is being supported by the project.

If you are developing micro-services, we suggest reading the https://developers.redhat.com/promotions/building-reactive-microservices-in-java/["Building Reactive Microservices in Java" book by Clément Escoffier].

== That's all folks!

We hope that you enjoyed reading this guide, and that it turned out to be useful in your journey towards asynchronous programming with Vert.x.

Feel-free to get in touch with the authors, either directly by email or through https://groups.google.com/forum/?fromgroups#!forum/vertx/[the Vert.x project user group].
Of course we appreciate praise, but we appreciate as much any constructive feedback that can improve this content.

Thank you very much!
