= 结尾

这是本指南的结尾。 让我们花点时间重述前几节中的重要内容，然后指出更多有用的资源。

== 概要

我们通过使用Vert.x构建wiki Web应用程序来开始本指南。虽然第一次迭代是 _"敏捷和杂乱的快速原型"_ 的典型代表，但它表明，可以快速轻松地构建这样一个应用程序，使用Web模板的服务器端渲染以及关系数据库的持久性。

接下来的步骤展示了如何通过连续的重构来改进设计：首先将每个技术关注点分离为独立的Verticle，然后提取Vert.x服务以获得简洁的API，最后介绍了对异步代码进行JUnit测试。

然后，我们开始使用Web客户端API来调用第三方HTTP/JSON服务，这进一步简化了Vert.x核心中HTTP客户端的使用。相反，我们还看到了如何使用优雅的Vert.x Web模块发布HTTP/JSON Web API。

从那里可以很容易地获得构建为许多服务提供对外接口的API网关的方法。如果你要建立这样的网关，我们建议你利用：

* Vert.x RxJava支持来描述服务消费数据流， 
* Vert.x断路器模块能够始终如一地处理服务的潜在故障。

Access control, authentication and security are often neglected or come as an aftermath.
We saw that Vert.x provides a simple pluggable authentication mechanism to leverage databases, files or LDAP directories.
SSL network encryption is very easy to setup for a server, or for a client to use.
Finally Vert.x supports JWT tokens, a very useful and decentralized authentication scheme for web APIs.

The Vert.x core API relies on callbacks as it is the most generic way of processing asynchronous events.
Vert.x provides a simple promise / future API.
While Vert.x futures are composable, they shall be confined to limited usages such as dealing with verticle deployments and initialization.
We saw how RxJava is supported in Vert.x, and we encourage you to use it for your own verticles.
What's more RxJava is the most popular reactive programming library on the JVM, so you will easily find third-party libraries to integrate consistently in your end-to-end reactive applications.

Modern web applications tend to have the server expose _just_ HTTP/JSON APIs, and rely on client-side web frameworks for the user interface.
We saw how to do that with AngularJS so as to turn our wiki into a single-page application.

Finally, we saw how elegant it was to extend the event bus of an application to allow web applications to send and receive events from the browser using the SockJS bridge.
While it may initially seem like to be a small feature, in practice it turns out to greatly simplify the development of _real-time_ web application features.
The SockJS bridge can actually be useful also in cases where one would have used an HTTP endpoint: sending a message then getting a response over the event bus can sometimes be simpler than doing an HTTP call, having the server process the HTTP request, forwarding it to a verticle on the event bus and eventually terminating the HTTP exchange by encoding a JSON response.

== Going further

The http://vertx.io/[Vert.x website] is of course the authority on all things Vert.x.

There are many features and modules that we haven't covered in this guide, such as:

* clustering using Hazelcast, Infinispan, Apache Ignite or Apache Zookeeper,
* how the code looks like with other supported languages,
* exposing and consuming over HTTP/2, possibly (but not necessarily) with gRPC 
* using NoSQL databases such as MongoDB or Redis,
* sending emails over SMTP,
* messaging with AMQP, Stomp, Kafka, MQTT or RabbitMQ,
* using OAuth2 authentication from custom and popular providers,
* Vert.x sync for writing blocking-style code that is later turned into _fibers_ non-blocking code at runtime,
* publishing and discovering micro-services from registries, for instance when deploying on cloud environments like OpenShift,
* exposing metrics and health checks.

This list is not exhaustive: Vert.x is a toolkit so you are the one to decide what ingredients are required for your project, big or small.

You may also find it useful to browse the https://github.com/vert-x3/vertx-awesome[Vert.x awesome] curated list of community projects as it goes beyond what is being supported by the project.

If you are developing micro-services, we suggest reading the https://developers.redhat.com/promotions/building-reactive-microservices-in-java/["Building Reactive Microservices in Java" book by Clément Escoffier].

== That's all folks!

We hope that you enjoyed reading this guide, and that it turned out to be useful in your journey towards asynchronous programming with Vert.x.

Feel-free to get in touch with the authors, either directly by email or through https://groups.google.com/forum/?fromgroups#!forum/vertx/[the Vert.x project user group].
Of course we appreciate praise, but we appreciate as much any constructive feedback that can improve this content.

Thank you very much!
