= 使用RxJava进行响应式编程

TIP: 相应的源代码位于指南存储库的 `step-8` 文件夹中。

到目前为止，我们已经使用基于回调的API探索了Vert.x堆栈的各个领域。 它只是能运行，并且这种编程模型在很多编程语言的开发人员中都是众所周知的。 然而，它可能会变得有点乏味，特别是当你结合几个事件源或处理复杂的数据流时。

这正是RxJava发挥的作用，Vert.x可以无缝集成它。

== 启用RxJava API

除了基于回调的API之外，Vert.x模块还提供了 _"Rxified"_ API。 要启用它，首先将 `vertx-rx-java` 模块添加到Maven POM文件中：

[source,xml,indent=0]
----
include::pom.xml[tags=vertx-rx-java]
----

Verticle必须进行修改，以便扩展 `io.vertx.rxjava.core.AbstractVerticle` 而不是  `io.vertx.core.AbstractVerticle` 。 这有什么不同？ 前一类扩展了后者，并发布了一个 `io.vertx.rxjava.core.Vertx` 字段。

`io.vertx.rxjava.core.Vertx` 定义了额外的 `rxSomething(...)` 方法，这些方法等同于基于回调的对应方法。

让我们来看看  `MainVerticle`  以更好地了解它在实践中的工作原理：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/MainVerticle.java[tags=rx-deploy-verticle]
----

`rxDeploy` 方法不会将 `Handler<AsyncResult<String>>` 作为最终参数。 相反，它返回一个 `Single<String>` 。

此外，调用该方法时操作不会启动。 它在您订阅 `Single` 时开始。 操作完成后，它会发出部署 `id` 或用 `Throwable` 指示问题的原因。

== 按顺序部署Verticle

为了完成 `MainVerticle` 重构，我们必须确保部署操作被触发并按顺序发生：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/MainVerticle.java[tags=rx-sequential-composition]
----
<1> `flatMap` 运算符将该函数应用于 `dbVerticleDeployment` 的结果。 它在这里安排 `HttpServerVerticle` 的部署。
<2> 订阅时开始操作。 在成功或出错时，`MainVerticle` 开始 future 将完成或失败。

== 部分 _"Rxifying"_ `HttpServerVerticle`

如果按顺序跟随指南，随时编辑代码，则您的 `HttpServerVerticle` 类仍在使用基于回调的API。 在您可以使用RxJava API _自然地_ （即同时）执行异步操作之前，您需要重构 `HttpServerVerticle` 。

=== 导入Vert.x类的RxJava版本

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/http/HttpServerVerticle.java[tags=rx-imports]
----
<1> 我们的 `backupHandler()` 方法仍然使用 `HttpResponse` 类，所以它必须被导入。 事实证明，由Vert.x提供的 `HttpResponse` 的RxJava版本可以作为这种特定情况下的直接替换。 指南存储库的 `step-8` 文件夹中的 _"Rxified"_ 代码不会导入此类，因为响应类型是由lambda表达式推断的。

=== 在 _"Rxified"_ `vertx` 实例上使用委托

要调用需要 `io.vertx.core.Vertx` 实例的方法(如果有 `io.vertx.rxjava.core.Vertx` 实例)，请调用getDelegate()方法。 在创建 `WikiDatabaseService` 的实例时需要调整Verticle的 `start()` 方法：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/http/HttpServerVerticle.java[tags=rx-vertx-delegate]
----

== 同时执行授权查询

在前面的例子中，我们看到了如何使用RxJava操作符和Rxified Vert.x API按顺序执行异步操作。 但有时候这种担保不是必需的，或者您只是希望它们为了性能原因而同时运行。

`HttpServerVerticle` 中的JWT令牌生成过程就是这种情况的一个很好的例子。 要创建令牌，我们需要获取所有授权查询结果，但所有查询彼此独立：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/http/HttpServerVerticle.java[tags=rx-concurrent-composition]
----
<1> 创建三个 `Single` 对象，表示不同的授权查询。Three `Single` objects are created, representing the different authorization queries.
<2> 当三个操作成功完成时，将使用结果调用 `zip` 运算符回调。

== 使用数据库连接

要从连接池中获取数据库连接，您只需在 `JDBCClient` 上调用 `rxGetConnection` ：

[source,java,indent=0]
----
Single<SQLConnection> connection = dbClient.rxGetConnection();
----

该方法返回一个 `Single<Connection>` ，您可以使用 `flatMap` 很容易转换成执行SQL查询：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/database/WikiDatabaseServiceImpl.java[tags=rx-execute-query-with-params]
----

但是如果 `SQLConnection` 引用不再可用，我们如何才能释放连接？ 一个简单而方便的方法是在 `Single<SQLConnection>` 取消订阅时调用 `close` ：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/database/WikiDatabaseServiceImpl.java[tags=rx-get-connection]
----
<1> 在获得连接后，我们将其包装成一个 `Single`
<2> `Single` 被修改为在退订时调用 `close`

现在，只要我们需要在数据库Verticle中执行SQL查询，就可以使用 `getConnection` 。

== 缩小回调和RxJava之间的差距

有时，您可能必须将RxJava代码与基于回调的API混合使用。 例如，服务代理接口只能用回调来定义，但用Vert.x Rxified API来实现。

在这种情况下， `io.vertx.rx.java.RxHelper` 类可以使 `Handler<AsyncResult<T>>` 适应RxJava的 `Subscriber<T>` ：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/database/WikiDatabaseServiceImpl.java[tags=rxhelper-to-subscriber]
----
<1> `fetchAllPagesData` 是一个异步服务代理操作，使用 `Handler<AsyncResult<List<JsonObject>>>` 回调定义。
<2> `toSubscriber` 方法将 `resultHandler` 调整为 `Subscriber<List<JsonObject>>` ，以便在发布行列表时调用处理器。

== 数据流

RxJava不仅善于组合不同的事件源，而且对数据流也非常有帮助。 与Vert.x或JDK future，`Observable` 发出一系列事件，而不仅仅是一个事件。 它配备了大量的数据操作操作符。

我们可以使用其中的一些来重构 `fetchAllPages` 数据库verticle方法：

[source,java,indent=0]
----
include::src/main/java/io/vertx/guides/wiki/database/WikiDatabaseServiceImpl.java[tags=rx-data-flow]
----
<1> 使用 `flatMapObservable` ，我们将从 `Single<Result>` 发出的项目创建一个 `Observable` 。
<2> 从将数据库 `结果` 可迭代转换为发布数据库行项目的 `Observable` 。
<3> 由于我们只需要页面名称，我们可以将每个 `JsonObject` 行 `映射` 到第一列。
<4> 客户期望数据按字母顺序排序。
<5> 事件总线服务应答包含在一个`JsonArray` 中。  `collect` 使用 `JsonArray::new` 创建一个新对象，随后使用 `JsonArray::add` 添加项目。
